version: '3'
services:
      mysql:

           image: mysql:5.7

           volumes:
                  - mysql_storage:/var/lib/mysql

           restart: always

           environment:
                    MYSQL_ROOT_PASSWORD: manas
                    MYSQL_USER: manas
                    MYSQL_USER_PASSWORD: redhat
                    MYSQL_DATABASE: webdb
      wordpress:
           image: wordpress:5.1.1-php7.3-apache
           depends_on:
                     - mysql
           restart: always
           ports:
                 - 8080:80
           environment:
                   WORDPRESS_DB_HOST: mysql
                   WORDPRESS_DB_USER: root
                   WORDPRESS_DB_PASSWORD: manas
                   WORDPRESS_DB_NAME: webdb
           volumes:
                 - wp_storage:/var/www/html

volumes:
        wp_storage:
        mysql_storage:
